name: 🚀 Deploy Website to Hostinger
on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Job:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      

      - name: 📂 Sync files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./api/
          # Upload into Hostinger public_html (FTP root)
          server-dir: ./
